---

- name: Install Bind & Bind Utils
  yum:
    pkg: ['bind','bind-utils']
    state: latest

- name: Modification /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^'
    line: "10.0.0.2  srv-dns01.domain.lan  srv-dns01"
    state: present

- name: Copy hostname Conf File
  template:
    src:  hostname
    dest: /etc/hostname

- name: Change DNS Address to 10.0.0.2
  replace:
    dest: /etc/sysconfig/network-scripts/ifcfg-enp0s3
    regexp: 'DNS1="8.8.8.8"'
    replace: 'DNS1="10.0.0.2"'

- name: Restart network
  service:
    name: network
    state: restarted

- name: Copy Named Conf File
  template:
    src:  named.conf
    dest: /etc/named.conf

- name: Copy Forward Zone File
  template:
    src:  db.domain.lan
    dest: /var/named/db.domain.lan

- name: Copy Reverse Zone File
  template:
    src:  db.0.0.10.in-addr.arpa
    dest: /var/named/db.0.0.10.in-addr.arpa

- name: Copy ddns.key File
  template:
    src:  ddns.key
    dest: /etc/named/ddns.key

- name: Open firewall port
  firewalld:
    service: dns
    permanent: true
    state: enabled
    immediate: yes

- name: Restart named
  service:
    name: named
    state: restarted